# Yarn 2+ configuration - DISABLED
# This project uses npm exclusively

# Disable yarn completely
enableGlobalCache: false
enableTelemetry: false
enableImmutableInstalls: false

# Force npm usage
packageManager: "npm@latest"
