services:
  - type: static
    name: bus-tracking-system
    buildCommand: npm ci && npm run build
    publishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
