services:
  - type: web
    name: bus-tracking-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
    autoDeploy: true
    pullRequestPreviewsEnabled: false
