#!/bin/bash

echo "🔧 Testing Background Location Tracking"
echo "======================================"

echo ""
echo "📱 Testing Service Worker Registration..."
echo "1. Open browser developer tools (F12)"
echo "2. Go to Application tab > Service Workers"
echo "3. Look for 'sw-location.js' registration"
echo ""

echo "🧪 Manual Test Steps:"
echo "====================="

echo ""
echo "Step 1: Driver Login & GPS Start"
echo "- Go to your frontend: https://bus-tracking-system-x9n6.vercel.app/login/driver"
echo "- Login with driver credentials"
echo "- Allow GPS permissions when prompted"
echo "- Verify green 'GPS Tracking Active' status"
echo ""

echo "Step 2: Check Console Logs"
echo "- Open browser console (F12 > Console)"
echo "- Look for these logs:"
echo "  ✅ '🚀 Starting enhanced background location tracking'"
echo "  ✅ '✅ Background location service worker registered'"
echo "  ✅ '📍 Driver GPS location captured (Dashboard)'"
echo ""

echo "Step 3: Test Screen Switching"
echo "- Keep driver logged in and GPS active"
echo "- Switch to a different browser tab"
echo "- Wait 15-20 seconds"
echo "- Switch back to driver tab"
echo "- Check console for background tracking logs:"
echo "  ✅ '📱 Page hidden - ensuring service worker takes over'"
echo "  ✅ '🚌 Background GPS captured (DRIVER ONLY)'"
echo ""

echo "Step 4: Test Student View Updates"
echo "- Open new tab/window"
echo "- Go to: https://bus-tracking-system-x9n6.vercel.app/login/student"
echo "- Login with student credentials"
echo "- Check if bus location updates even when driver tab is hidden"
echo ""

echo "Step 5: Test App Switching (Mobile)"
echo "- On mobile: Switch to another app (WhatsApp, etc.)"
echo "- Wait 30 seconds"
echo "- Switch back to browser"
echo "- Verify GPS tracking continued"
echo ""

echo "🔍 Debugging Commands:"
echo "====================="

echo ""
echo "Check Service Worker Status:"
echo "navigator.serviceWorker.getRegistrations().then(regs => console.log('SW Registrations:', regs))"
echo ""

echo "Check Background Tracking Status:"
echo "console.log('Stored Driver:', JSON.parse(localStorage.getItem('backgroundTrackingDriver') || '{}'))"
echo ""

echo "Check Latest Location:"
echo "console.log('Latest Location:', JSON.parse(localStorage.getItem('latest_location_66d0123456a1b2c3d4e5f601') || '{}'))"
echo ""

echo "Force Service Worker Message:"
echo "navigator.serviceWorker.controller?.postMessage({type: 'START_TRACKING', data: {busId: '66d0123456a1b2c3d4e5f601', name: 'Test Driver'}})"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ Service worker registered successfully"
echo "✅ GPS permissions granted"
echo "✅ Location updates continue when tab is hidden"
echo "✅ Students see updated location across devices"
echo "✅ Console shows background tracking logs"
echo "✅ Location persists across browser sessions"
echo ""

echo "🚨 Troubleshooting:"
echo "==================="
echo "❌ If service worker fails:"
echo "   - Check HTTPS (required for service workers)"
echo "   - Clear browser cache and reload"
echo "   - Check browser console for errors"
echo ""
echo "❌ If GPS stops when switching tabs:"
echo "   - Verify service worker is active"
echo "   - Check browser's background tab throttling settings"
echo "   - Test on different browsers (Chrome, Firefox, Safari)"
echo ""
echo "❌ If location not updating:"
echo "   - Check GPS permissions"
echo "   - Verify driver source validation"
echo "   - Check backend API connectivity"
echo ""

echo "🔗 Quick Test URLs:"
echo "=================="
echo "Driver Login: https://bus-tracking-system-x9n6.vercel.app/login/driver"
echo "Student Login: https://bus-tracking-system-x9n6.vercel.app/login/student"
echo "Live Map: https://bus-tracking-system-x9n6.vercel.app/live-map"
echo "Backend API: https://bus-tracking-system-4.onrender.com/api/location/all-locations"
echo ""

echo "✨ Background location tracking test guide ready!"
echo "Follow the steps above to verify your GPS tracking works across screen switches."
